### ISSUE TITLE
Put vendored gx dep. at top level

### ISSUE THREAD

**Issue by kevina** [ipfs/fs-repo-migrations#74]
Right now there are a large number of vendored gx dependencies in `fs-repo-migrations/ipfs-6-to-7/vendor/gx/ipfs/'.  Could we move those to `fs-repo-migrations/vendor/gx/ipfs/`.

I need to make use of many of the same gx deps. in my migration code and want to avoid checking in the same files in two places.

CC @Stebalien

**Comment by Stebalien** [comment]
So, to reduce the size of the repo, I trimmed those deps down to exactly what I needed (stripping unused packages). If we move that up, we'll have to import the *full* deps. We can do that, it's just large (90MiB versus 15MiB, IIRC).

However, you're probably right. Feel free to move them.

Note: I figured that any future migrations will use different gx deps as they'll likely depend on different go-ipfs versions. Obviously, that's not the case here. Regardless, gx deps *are* frozen is it does kind of make sense to put them at the top level.

---

Personally, I'd like to switch to `gx` but @whyrusleeping wants this repo to be go-gettable (for good reason).

**Comment by kevina** [comment]
> If we move that up, we'll have to import the full deps.

Can missing packages within a gx dep, cause a change in behavior that does not result in an error.  If the only change is an error I don't see a problem with leaving them incomplete, if parts a package is missing it can be added later.

If it is necessary to vendor the full deps, than maybe we should keep them where they are and possible use symbolic links, although I am not sure if that will work on windows.

**Comment by Stebalien** [comment]
> Can missing packages within a gx dep, cause a change in behavior that does not result in an error. If the only change is an error I don't see a problem with leaving them incomplete, if parts a package is missing it can be added later.

I don't think so... the main worry is that we should avoid *changing* existing migrations after creating them. We don't want to update the deps and silently break some old migration (can't assume the test cases will catch everything).

In this case, it's not an issue because:

1. We *just* added the 6-7 migration.
2. We're *deliberately* changing a previous migration.

I'm mostly worried about accidental changes to old migrations.

---

> If it is necessary to vendor the full deps, than maybe we should keep them where they are and possible use symbolic links, although I am not sure if that will work on windows.

It won't.

---

Honestly, this whole vendor "cleaning" thing probably isn't worth it. I had to jump through hoops to make sure I got all the packages required by all platforms we support and probably missed platforms we don't support but that would otherwise work. Let's just move the gx deps to the root and not bother cleaning them (well, we can probably remove `*_test.go` files and friends).

**Comment by kevina** [comment]
@whyrusleeping the problem is we need just hand picking the gx deps, but leaving out packages within a dependency, espacally inside the `go-ipfs` dep.  If we do this at the top level, this could create a potential conflict if that dependency is used by another version of the migration tool.  I am already running in his problem with the `6-to-7` migration tool I am working on.
